### ISSUE TITLE
`Primefaces Poseidon` on browser's tab label

### ISSUE THREAD

**Issue by jxmai** [primefaces/atlantis#8]
Running any of the sample code from #6 or #7 

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/22565904/84ef70ea-e94f-11e6-9145-aa8f5819dde7.png)

Please fix the temple

```xhtml
<title><ui:insert name="title">PrimeFaces Poseidon</ui:insert></title>
```

---

Enviroment:

Primefaces 6.0.13
Altantis 1.0.1
Chrome 56.0.2924.87 (64-bit)

**Comment by mertsincan** [comment]
You can change the title in your page;
in sample.xhtml
<ui:define name="title">Sample</ui:define>

**Comment by jxmai** [comment]
Thanks, but the `Primefaces Poseidon` title is under `Primefaces Atlantis` template. Although user should change the title anyway, this tiny cosmetic issue could be fixed fairly easily.
